### ISSUE TITLE
生成的iconfont css 的 font-size: 最好是1em

### ISSUE THREAD

**Issue by tutusiji** [amazecc/iconfont-spanner#4]
.iconfont {
    font-family: "iconfont" !important;
    font-size: 16px;
    font-style: normal;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

**Comment by amazecc** [comment]
[v2.4.0](https://github.com/amazecc/iconfont-spanner/releases/tag/v2.4.0)
已经处理，删除了 font-szie, 并且支持了样式自定义
