### ISSUE TITLE
本地原本的彩色svgicon在svg component 选项卡里面也应该是保持原本的彩色

### ISSUE THREAD

**Issue by tutusiji** [amazecc/iconfont-spanner#5]
![image](https://github.com/user-attachments/assets/345e9de8-e0ff-42e4-8d9e-3f7c92ea11e5)
![image](https://github.com/user-attachments/assets/e731e11f-9b26-4bc4-9d19-62ce912d01a7)

**Comment by amazecc** [comment]
由于大部分的图标都是纯色的，彩色图标的场景比较少，所以，默认会将 svg 的 fill 属性改成 currentColor，如果需要保留 svg 原本的颜色，可以在文件名做上标记，比如以 ’_oc‘ 结尾的文件，保留原色：
<img width="787" alt="image" src="https://github.com/user-attachments/assets/5c911f3c-3c04-4914-b1ff-f24d1dad0689">
